
CREATE TABLE [dbo].[UIPathProcessReport](
	[TransactionID] [int] IDENTITY(1,1) NOT NULL,
	[TransactionName] [varchar](max) NULL,
	[ProcessName] [varchar](max) NOT NULL,
	[StartTime] [datetime] NOT NULL,
	[EndTime] [datetime] NULL,
	[TransactionStatus] [varchar](max) NOT NULL
)

GO
CREATE OR ALTER PROCEDURE AVGTRANSACTIONPERJOB @PROCESSNAME VARCHAR(max),@STARTTIME DATETIME,@ENDTIME DATETIME
AS
BEGIN
if @STARTTIME is null 
 set @STARTTIME='2019-1-1'
if @ENDTIME is null 
 set @ENDTIME=GETDATE()
 IF @PROCESSNAME='ALL'
	SELECT 'NA'
	ELSE
	BEGIN
DECLARE @NUMBEROFTRANSACTIONS DECIMAL(8,2),@NUMBEROFJOBS DECIMAL(8,2),@AVGTRANSACTIONPERJOB DECIMAL(8,2);
IF exists (select * from UIPathProcessReport where ProcessName=@PROCESSNAME and StartTime between @STARTTIME and @ENDTIME)
BEGIN
 SET @NUMBEROFTRANSACTIONS= (SELECT COUNT(*) FROM UIPathProcessReport WHERE TransactionName IS NOT NULL AND ProcessName=@PROCESSNAME and StartTime BETWEEN @STARTTIME AND @ENDTIME);
 SET @NUMBEROFJOBS= (SELECT COUNT(*) FROM UIPathProcessReport WHERE TransactionName IS NULL AND ProcessName=@PROCESSNAME and StartTime BETWEEN @STARTTIME AND @ENDTIME);
 SET @AVGTRANSACTIONPERJOB=@NUMBEROFTRANSACTIONS/@NUMBEROFJOBS;
 Select @AVGTRANSACTIONPERJOB;
END
ELSE
BEGIN
SET @AVGTRANSACTIONPERJOB=0;
Select @AVGTRANSACTIONPERJOB;
END
END
END
GO


GO
CREATE OR ALTER PROCEDURE AVGTRANSACTIONEXECUTIONTIME @PROCESSNAME VARCHAR(max),@STARTTIME DATETIME,@ENDTIME DATETIME
AS
BEGIN
	if @STARTTIME is null 
		set @STARTTIME='2019-1-1'
	if @ENDTIME is null 
		set @ENDTIME=GETDATE()
	if @PROCESSNAME='ALL'
	BEGIN
		SELECT 'NA'
	END
ELSE
BEGIN
DECLARE @NUMBEROFTRANSACTIONS DECIMAL(8,2),@SUMOFEXECUTIONTIME DECIMAL(8,2),@AVGTRANSACTIONEXECUTIONTIME DECIMAL(8,2);
IF exists (select * from UIPathProcessReport where ProcessName=@PROCESSNAME and StartTime between @STARTTIME and @ENDTIME )
BEGIN
 SET @NUMBEROFTRANSACTIONS= (SELECT COUNT(*) FROM UIPathProcessReport WHERE TransactionName IS NOT NULL AND ProcessName=@PROCESSNAME and StartTime BETWEEN @STARTTIME AND @ENDTIME);
 SET @SUMOFEXECUTIONTIME= (SELECT SUM(DATEDIFF(MINUTE,StartTime,EndTime)) FROM UIPathProcessReport WHERE TransactionName IS NOT NULL AND ENDTIME IS NOT NULL AND ProcessName=@PROCESSNAME  and StartTime BETWEEN @STARTTIME AND @ENDTIME);
 SET @AVGTRANSACTIONEXECUTIONTIME=@SUMOFEXECUTIONTIME/@NUMBEROFTRANSACTIONS;
 Select @AVGTRANSACTIONEXECUTIONTIME;
END
ELSE
BEGIN
SET @AVGTRANSACTIONEXECUTIONTIME=0;
Select @AVGTRANSACTIONEXECUTIONTIME;
END
END
END

GO





GO
CREATE OR ALTER PROCEDURE NUMBEROFJOBSPROCESSED @PROCESSNAME VARCHAR(max),@STARTTIME DATETIME,@ENDTIME DATETIME,@NUMBEROFJOBSPROCESSED INT OUTPUT
AS
BEGIN
if @STARTTIME is null 
 set @STARTTIME='2019-1-1'
if @ENDTIME is null 
 set @ENDTIME=GETDATE()
IF @PROCESSNAME='ALL'
SET @NUMBEROFJOBSPROCESSED= (SELECT COUNT(*) FROM UIPathProcessReport WHERE TransactionName IS NULL)
ELSE
	BEGIN
		IF EXISTS(SELECT * FROM UIPathProcessReport WHERE TransactionName IS NULL AND ProcessName=@PROCESSNAME and StartTime BETWEEN @STARTTIME AND @ENDTIME)
		SET @NUMBEROFJOBSPROCESSED=(SELECT COUNT(*) FROM UIPathProcessReport WHERE TransactionName IS NULL AND ProcessName=@PROCESSNAME  and StartTime BETWEEN @STARTTIME AND @ENDTIME)
		ELSE
		SET @NUMBEROFJOBSPROCESSED=0
	END
RETURN @NUMBEROFJOBSPROCESSED
END
GO


GO
CREATE OR ALTER PROCEDURE NUMBEROFTRANSACTIONPROCESSED @PROCESSNAME VARCHAR(max),@STARTTIME DATETIME,@ENDTIME DATETIME,@NUMBEROFTRANSACTIONPROCESSED INT OUTPUT
AS
BEGIN
if @STARTTIME is null 
 set @STARTTIME='2019-1-1'
if @ENDTIME is null 
 set @ENDTIME=GETDATE()
IF @PROCESSNAME='ALL'
SET @NUMBEROFTRANSACTIONPROCESSED= (SELECT COUNT(*) FROM UIPathProcessReport WHERE TransactionName IS NOT NULL AND ENDTIME IS NOT NULL  and StartTime BETWEEN @STARTTIME AND @ENDTIME)
ELSE
	BEGIN
		IF EXISTS(SELECT * FROM UIPathProcessReport WHERE TransactionName IS NULL AND ProcessName=@PROCESSNAME and StartTime BETWEEN @STARTTIME AND @ENDTIME)
		SET @NUMBEROFTRANSACTIONPROCESSED=(SELECT COUNT(*) FROM UIPathProcessReport WHERE TransactionName IS NOT NULL AND ENDTIME IS NOT NULL AND ProcessName=@PROCESSNAME  and StartTime BETWEEN @STARTTIME AND @ENDTIME)
		ELSE
		SET @NUMBEROFTRANSACTIONPROCESSED=0
	END
RETURN @NUMBEROFTRANSACTIONPROCESSED
END
GO

GO
CREATE OR ALTER PROCEDURE TRANSACTIONSTATS @PROCESSNAME VARCHAR(max),@STARTTIME DATETIME,@ENDTIME DATETIME,@NUMBEROFSUCCESSFULTRANSACTION INT OUTPUT,@NUMBEROFFAULTEDTRANSACTION INT OUTPUT,@NUMBEROFINPROGRESSTRANSACTION INT OUTPUT,@NUMBEROFRULEEXCEPTIONSTRANSACTION INT OUTPUT
AS
BEGIN
if @STARTTIME is null 
 set @STARTTIME='2019-1-1'
 else
 set @STARTTIME=FORMAT (@STARTTIME, 'd', 'en-US') 

if @ENDTIME is null 
 set @ENDTIME=GETDATE()
  else
 set @ENDTIME=FORMAT (@ENDTIME, 'd', 'en-US') 
IF @PROCESSNAME='ALL'
	BEGIN
		SET @NUMBEROFSUCCESSFULTRANSACTION= (SELECT COUNT(*) FROM UIPathProcessReport WHERE TransactionName IS NOT NULL AND ENDTIME IS NOT NULL AND TransactionStatus='SUCCESS' and StartTime BETWEEN @STARTTIME AND @ENDTIME)
		SET @NUMBEROFINPROGRESSTRANSACTION= (SELECT COUNT(*) FROM UIPathProcessReport WHERE TransactionName IS NOT NULL AND TransactionStatus='INPROGRESS' and StartTime BETWEEN @STARTTIME AND @ENDTIME)
		SET @NUMBEROFFAULTEDTRANSACTION= (SELECT COUNT(*) FROM UIPathProcessReport WHERE TransactionName IS NOT NULL AND ENDTIME IS NOT NULL AND TransactionStatus='FAULTED' and StartTime BETWEEN @STARTTIME AND @ENDTIME)
		SET @NUMBEROFRULEEXCEPTIONSTRANSACTION= (SELECT COUNT(*) FROM UIPathProcessReport WHERE TransactionName IS NOT NULL AND ENDTIME IS NOT NULL AND TransactionStatus='RULEEXCEPTION' and StartTime BETWEEN @STARTTIME AND @ENDTIME)
	END
ELSE
	BEGIN
		IF EXISTS(SELECT * FROM UIPathProcessReport WHERE TransactionName IS NULL AND ProcessName=@PROCESSNAME)
			BEGIN
				SET @NUMBEROFSUCCESSFULTRANSACTION= (SELECT COUNT(*) FROM UIPathProcessReport WHERE TransactionName IS NOT NULL AND ENDTIME IS NOT NULL AND TransactionStatus='SUCCESS' AND ProcessName=@PROCESSNAME and StartTime BETWEEN @STARTTIME AND @ENDTIME)
				SET	@NUMBEROFINPROGRESSTRANSACTION= (SELECT COUNT(*) FROM UIPathProcessReport WHERE TransactionName IS NOT NULL AND TransactionStatus='INPROGRESS' AND ProcessName=@PROCESSNAME AND ProcessName=@PROCESSNAME and StartTime BETWEEN @STARTTIME AND @ENDTIME)
				SET @NUMBEROFFAULTEDTRANSACTION= (SELECT COUNT(*) FROM UIPathProcessReport WHERE TransactionName IS NOT NULL AND ENDTIME IS NOT NULL AND TransactionStatus='FAULTED' AND ProcessName=@PROCESSNAME and StartTime BETWEEN @STARTTIME AND @ENDTIME)
				SET @NUMBEROFRULEEXCEPTIONSTRANSACTION= (SELECT COUNT(*) FROM UIPathProcessReport WHERE TransactionName IS NOT NULL AND ENDTIME IS NOT NULL AND TransactionStatus='RULEEXCEPTION' AND ProcessName=@PROCESSNAME and StartTime BETWEEN @STARTTIME AND @ENDTIME)
			END
		ELSE
		BEGIN
			SET @NUMBEROFSUCCESSFULTRANSACTION=0
			SET	@NUMBEROFINPROGRESSTRANSACTION=0
			SET @NUMBEROFFAULTEDTRANSACTION=0
			SET @NUMBEROFRULEEXCEPTIONSTRANSACTION=0
		END
	END
END
GO

GO
CREATE OR ALTER PROCEDURE BOTUTILIZATION @PROCESSNAME VARCHAR(max),@STARTTIME DATETIME,@ENDTIME DATETIME,@TIMECONSUMED INT OUTPUT
AS
BEGIN
DECLARE @SUMOFEXECUTIONTIME DECIMAL(8,2)
IF @PROCESSNAME='ALL'
BEGIN 
 SET @TIMECONSUMED= (SELECT SUM(DATEDIFF(SECOND,StartTime,EndTime)) FROM UIPathProcessReport WHERE TransactionName IS NOT NULL AND ENDTIME IS NOT NULL and StartTime BETWEEN @STARTTIME AND @ENDTIME);
END
ELSE
BEGIN
IF exists (select * from UIPathProcessReport where ProcessName=@PROCESSNAME)
 SET @TIMECONSUMED= (SELECT SUM(DATEDIFF(SECOND ,StartTime,EndTime)) FROM UIPathProcessReport WHERE TransactionName IS NOT NULL AND ENDTIME IS NOT NULL AND ProcessName=@PROCESSNAME  and StartTime BETWEEN @STARTTIME AND @ENDTIME);
 ELSE
 SET @TIMECONSUMED=0;
 END
END

GO

